version: 1
project:
  root: .
  build_config: lzc-build.yml
  package_file: package.yml
  output: dist/voapi.lpk
update:
  strategy: publish
  allow_downgrade: false
  version_source:
    type: image
    image: voapi
build:
  run_buildscript: false
images:
  - id: voapi
    target: service
    service: voapi
    source: voapi/voapi
    channel: custom
    sort: semver
    tag_regex: '^v1\.2\.0$'
    version_regex: '^v(?P<version>[0-9]+\.[0-9]+\.[0-9]+)$'
    version_template: '{version}'
    delivery:
      mode: lazycat
  - id: redis
    target: service
    service: redis
    source: redis
    channel: custom
    sort: created
    tag_regex: '^latest$'
    version_regex: '^(?P<version>latest)$'
    version_template: '0.10.0'
    delivery:
      mode: lazycat
stores:
  official:
    enabled: true
    skip_if_version_exists: true
  private:
    enabled: true
    skip_if_version_exists: true
    name: VoAPI
    summary: 高颜值、高性能的 AI 模型接口管理与分发系统
