application:
  subdomain: voapi
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://voapi:3000/
services:
  voapi:
    # upstream: voapi/voapi:v1.2.0
    image: registry.lazycat.cloud/czyt/voapi/voapi:9029a3c87a109ca1
    environment:
      - TZ=Asia/Shanghai
      - REDIS_CONN_STRING=redis://redis
      - SESSION_SECRET=y9IPRKC9ZcTp7g4D9vJQ8vDBW8W+N1eK1B/l5f4zUoaUALoU9gGyEHFYSZOFWtgegS6MF8F4iL3WANFLPXqDLA==
    binds:
      - /lzcapp/var/data:/data
      - /lzcapp/var/logs:/app/logs
    depends_on:
      - redis
    healthcheck:
      test:
        - CMD-SHELL
        - "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $2}'"
      start_period: 90s
  redis:
    # upstream: redis:latest
    image: registry.lazycat.cloud/czyt/library/redis:a570833824bde283
    healthcheck:
      test:
        - CMD-SHELL
        - redis-cli ping
      start_period: 30s
